services:
  db:
    image: postgres:latest
    container_name: pizzaria_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pizzaria_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile.api
    container_name: pizzaria_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "${API_PORT}:80"


    #web:
    #  build:
    #   context: ../web
    #  dockerfile: docker/Dockerfile.web
    #container_name: pizzaria_front
    #ports:
    #  - "${WEB_PORT}:80"
    # depends_on:
    #   - api

volumes:
  pgdata:
