version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pizzaria_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pizzaria_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile.api
    container_name: pizzaria_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=pizzaria_db;Username=admin;Password=admin
    ports:
      - "5093:80"

volumes:
  pgdata:
