services:
  db:
    image: postgres:15
    container_name: pizzaria_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile.api
    container_name: pizzaria_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "${API_PORT}:80"


    #web:
    #  build:
    #   context: ../web
    #  dockerfile: docker/Dockerfile.web
    #container_name: pizzaria_front
    #ports:
    #  - "${WEB_PORT}:80"
    # depends_on:
    #   - api

volumes:
  pgdata:
